str = "asdf"

print(len(str))
print(str[0])
print(str[1])
print(str[2])
print(str[3])

str = "a'\"\"'\\b"
print(len(str))
print(str[0])
print(str[1])
print(str[2])
print(str[3])
print(str[4])
print(str[5])
print(str[6])
print(str[7])

str = 'q1'
print(len(str))
print(str[0])
print(str[1])

str = '0"\\\'\'"1'
print(len(str))
print(str[0])
print(str[1])
print(str[2])
print(str[3])
print(str[4])
print(str[5])
print(str[6])
print(str[7])
