ASTNode = require('./src/ast_node')
fixOpPrecedence = require('./src/tree_arrange/fix_op_precedence')
replaceOpsWithFns = require('./src/tree_arrange/replace_ops_with_fns')
genASTIds = require('./src/tree_arrange/gen_ast_ids')
genTypeInfo = require('./src/gen_type_info')
Parser = require('./src/parser')
Scope = require('./src/scope')

fs = require('fs')
inputStr = fs.readFileSync(process.argv[2]).toString()

parser = new Parser()

astTree = parser.parse(inputStr)
astTree = fixOpPrecedence(astTree)
astTree = replaceOpsWithFns(astTree)
astTree = genASTIds(astTree)
typeInfo = genTypeInfo(astTree)
console.log(JSON.stringify(typeInfo, null, 2))
#astTree.genSymbols(new Scope('global', null))
#console.log(JSON.stringify(ASTNode.getScopes(astTree), null, 2))
#console.log(astTree.genWast())
